### ISSUE TITLE
Realizar formato de entrevista

### ISSUE THREAD

**Issue by djrock1987** [ISWPOLI/EPPSOFT#1]
Prioridad Alta

**Comment by Juancho47** [comment]
- [ ] hola mundo

**Comment by Juancho47** [comment]
Te puedes basar en este formato de entrevista
[reqini.pdf](https://github.com/ISWPOLI/EPPSOFT/files/1265590/reqini.pdf)

**Comment by divelasquez** [comment]
[Formato entrevista Resuelto.docx](https://github.com/ISWPOLI/EPPSOFT/files/1346908/Formato.entrevista.Resuelto.docx)
