### ISSUE TITLE
1. Levantamiento

### ISSUE THREAD

**Issue by Juancho47** [ISWPOLI/EPPSOFT#13]

**Comment by divelasquez** [comment]
Se adjunta documentación del levantamiento de información.
[Formato entrevista Resuelto.docx](https://github.com/ISWPOLI/EPPSOFT/files/1469024/Formato.entrevista.Resuelto.docx)
[formato_ieee830.docx](https://github.com/ISWPOLI/EPPSOFT/files/1469025/formato_ieee830.docx)
