### ISSUE TITLE
Creación prototipo Desktop 

### ISSUE THREAD

**Issue by Juancho47** [ISWPOLI/EPPSOFT#22]

**Comment by divelasquez** [comment]
Adelanto de prototipos
[PrototipoEppSoft.docx](https://github.com/ISWPOLI/EPPSOFT/files/1469275/PrototipoEppSoft.docx)

**Comment by divelasquez** [comment]
Se realiza la entrega del prototipo Desktop
[PrototipoEppSoft.docx](https://github.com/ISWPOLI/EPPSOFT/files/1497809/PrototipoEppSoft.docx)
