### ISSUE TITLE
Creación prototipo móvil 

### ISSUE THREAD

**Issue by Juancho47** [ISWPOLI/EPPSOFT#23]

**Comment by divelasquez** [comment]
[MockupsMovilEppSoft.docx](https://github.com/ISWPOLI/EPPSOFT/files/1377407/MockupsMovilEppSoft.docx)

**Comment by divelasquez** [comment]
Se sube el prototipo móvil.
[MockupsMovilEppSoft.docx](https://github.com/ISWPOLI/EPPSOFT/files/1486373/MockupsMovilEppSoft.docx)
