### ISSUE TITLE
Crear documento de analisis de requerimientos 

### ISSUE THREAD

**Issue by djrock1987** [ISWPOLI/EPPSOFT#3]
- identificar requerimient de negocio
- identificar requerimiento tecnico
- identificar requerimientos funcionales 
- identificar requerimientos no funcionales

_Sent from my Samsung SM-G610M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by divelasquez** [comment]
[formato_ieee830.doc.docx](https://github.com/ISWPOLI/EPPSOFT/files/1351301/formato_ieee830.doc.docx)

**Comment by divelasquez** [comment]
[formato_ieee830.doc.docx](https://github.com/ISWPOLI/EPPSOFT/files/1374269/formato_ieee830.doc.docx)
