### ISSUE TITLE
Objetivos Smart

### ISSUE THREAD

**Issue by djrock1987** [ISWPOLI/EPPSOFT#36]

**Comment by divelasquez** [comment]
[DocumentacionEPPSOFT.docx](https://github.com/ISWPOLI/EPPSOFT/files/1351171/DocumentacionEPPSOFT.docx)

**Comment by divelasquez** [comment]
![objetivo smart](https://user-images.githubusercontent.com/30845765/31423304-9e66d132-ae19-11e7-9c3a-e62cc6dc5017.png)
