### ISSUE TITLE
AVANCE 1

### ISSUE THREAD

**Issue by djrock1987** [ISWPOLI/EPPSOFT#45]

**Comment by Juancho47** [comment]
Se arma la estructura basica del proyecto, sera implementado en un framework de php,  symfony 3, con un patron de diseño de software Modelo Vista Controlador.

Utilizando framework complementarios como lo son Doctrine.
Se arma arquitectura de carpetas, esta siendo en un entorno de desarrollo con netbeans 8.1
![image](https://user-images.githubusercontent.com/5251986/31098699-219c0780-a789-11e7-9b7d-750918b051e8.png)
