### ISSUE TITLE
Set de pruebas funcionales

### ISSUE THREAD

**Issue by djrock1987** [ISWPOLI/EPPSOFT#49]

**Comment by divelasquez** [comment]
Se están realizando las pruebas funcionales.
[Set de pruebas.xlsx](https://github.com/ISWPOLI/EPPSOFT/files/1486374/Set.de.pruebas.xlsx)

**Comment by divelasquez** [comment]
Se actualiza el Set de pruebas.
[Uploading Set de pruebas.xlsx…]()

**Comment by divelasquez** [comment]
Se realiza la entrega del Set de Pruebas.
[Set de pruebas.xlsx](https://github.com/ISWPOLI/EPPSOFT/files/1497806/Set.de.pruebas.xlsx)
