### ISSUE TITLE
Creacion de prototipo

### ISSUE THREAD

**Issue by djrock1987** [ISWPOLI/EPPSOFT#6]

**Comment by divelasquez** [comment]
Prototipos principales
![prototiporeplantilla](https://user-images.githubusercontent.com/30845765/32758406-3eee785a-c8b2-11e7-8346-e3a1dc9b03fa.png)
![prototipologin](https://user-images.githubusercontent.com/30845765/32758407-3f121562-c8b2-11e7-9ce1-e97ea08af1dd.png)
![prototiporepplantilla](https://user-images.githubusercontent.com/30845765/32758408-3f45f080-c8b2-11e7-8248-2b1676ea1ed0.png)
